### ISSUE TITLE
new page

### ISSUE THREAD

**Issue by jointhepartypooper** [peercoin/docs#15]
I am unable to push to master. So here is a draft of a new page:

# Peercoin proof of stake

>Peercoin uses both the Proof-of-Work and Proof-of-Stake algorithms. The PoW algorithm is used to spread the distribution of new coins. Up to 99% of all peercoins is created with POW. Proof-of-Stake is used to secure the network: The chain with longest POS coin age wins in case of a blockchain split-up.

Minting, as it is called in peercoin to make a proof of stake block, is based on metrics of an unspent transaction. If we take a look at the number one spot of the rich list, transaction c7293fc60c80bdcc374775d1f0734e0766465b905bae1a312fe487793be3b8f7 has among others the following characteristics:

* The transaction appeared in block 376161 at timestamp 1531750952 (Unix time).
* The transaction in the block has an offset of 383 bytes. It is the third transaction in the block. The size of the first two transactions in the block are respectively 78 and 224 bytes.  
* The transaction timestamp is 1531750624.
* The second recipient (index 1) received 1786301.06651300 peercoins which, at the moment, is still unspent.

These metrics, along with two more data points serves as a basis to calculate a hash for POS minting: 

* a future timestamp X (in unix time notation) in which the stake could win.
* a block modifier that was set by the network 1830080 seconds (~21 days) earlier than X. Every 6 hours the network calculates a new block modifier to be used for POS minting. 

The win in Proof of stake minting, the calculated hash is compared to the current difficulty minus the coinage. The chances of finding a stake therefor improves when either the coinage increases or when the difficulty of the network decreases. 

## Peercoin minting behaviour

* Minting process can only start after 30 days of coinage.
* Minting coinage is maxed out after 90 days. Which means that after 90 days the only variable left in POS is the current difficulty.
* Minting is predictable and not random. For a given transaction, you can calculate the maximum network PoS diff over time for your transaction to be able to mint a PoS block. Whenever this PoS diff is higher than the current network PoS diff your Peercoin client can mint a PoS block.
* PoS blocks can be rejected (orphans) if several people mint a PoS block within a given window (2 hours also called timedrift). Only one (the chain with longest coin age) will be accepted.
* Minting splits the transaction in two if coinage < 90 days.  
* PoS block reward is 1% annual. This 1% is factor of your coinage, and is not maxed out.
* A transaction that just staked has its coins locked for 520 confirmations (3-4 days).
* Merging transactions, spending coins, etc. burns coinage (resets it to 0).
* PoS reward is directly added to your transaction which staked (if this transaction is split in two because coinage < 90 days, the reward is equally distributed to both resulting transactions).

**Comment by peerchemist** [comment]
> I am unable to push to master.

You fork it and push the PR back here.

**Comment by peerchemist** [comment]
I've pushed it to repo.
